//! What Romlens's level 1 and 2 questions ask (docs/28): numbers traced to
//! the core's constants and tables, statements with their wrong answers,
//! and each concept's registers, instructions and glossary terms.
//!
//! Every entry is checked by `claims`: a number against its table, a
//! register or instruction against the core's. The statements are ours,
//! in the primer's words (`04-snes-technical-primer.md`).

/// A number to know.
pub struct Number {
    pub id: &'static str,
    pub concept: &'static str,
    pub level: u8,
    pub prompt: &'static str,
    pub answer: u32,
    /// Typed and shown as hex (an address).
    pub hex: bool,
    pub explain: &'static str,
}

const fn n(
    id: &'static str,
    concept: &'static str,
    level: u8,
    prompt: &'static str,
    answer: u32,
    explain: &'static str,
) -> Number {
    Number {
        id,
        concept,
        level,
        prompt,
        answer,
        hex: false,
        explain,
    }
}

const fn h(
    id: &'static str,
    concept: &'static str,
    level: u8,
    prompt: &'static str,
    answer: u32,
    explain: &'static str,
) -> Number {
    Number {
        id,
        concept,
        level,
        prompt,
        answer,
        hex: true,
        explain,
    }
}

pub const NUMBERS: &[Number] = &[
    // The machine.
    n(
        "bank_kb",
        "banks",
        1,
        "How many kilobytes is one bank of the 65816's address space?",
        64,
        "An address is a bank byte and 16 bits within it, so each of the 256 banks is 64 KB.",
    ),
    n(
        "address_bits",
        "cpu",
        2,
        "How many bits wide is the 65816's address?",
        24,
        "A bank byte and a 16-bit address: 24 bits, 16 MB of address space.",
    ),
    n(
        "banks",
        "memory_map",
        2,
        "How many banks does the 65816's address space have?",
        256,
        "The bank byte is 8 bits: banks $00 to $FF, 64 KB each.",
    ),
    n(
        "wram_kb",
        "wram",
        2,
        "How many kilobytes of work RAM does the SNES have?",
        128,
        "WRAM is 128 KB, at $7E:0000–$7F:FFFF.",
    ),
    n(
        "wram_mirror",
        "wram",
        2,
        "How many bytes of WRAM also appear at $0000 in banks $00–$3F?",
        8192,
        "The first 8 KB of WRAM is mirrored low in the system banks, so short addresses reach it from any of them.",
    ),
    n(
        "spc_khz",
        "apu",
        2,
        "At about how many kHz does the SPC700 run?",
        1024,
        "The APU's 24.576 MHz clock divided by 24: about 1.024 MHz.",
    ),
    n(
        "aram_kb",
        "apu",
        2,
        "How many kilobytes of RAM does the sound CPU have?",
        64,
        "ARAM is 64 KB, holding the sound driver, the samples and the echo buffer.",
    ),
    n(
        "lorom_bank",
        "mapping",
        2,
        "How many bytes of ROM does one LoROM bank show?",
        32768,
        "LoROM shows 32 KB of ROM in the upper half, $8000–$FFFF, of each bank.",
    ),
    n(
        "hirom_bank",
        "mapping",
        2,
        "How many bytes of ROM does one HiROM bank at $C0–$FF show?",
        65536,
        "HiROM shows whole 64 KB banks at $C0–$FF.",
    ),
    h(
        "header_lorom",
        "rom",
        2,
        "At which file offset is a LoROM game's internal header?",
        0x7FC0,
        "The header sits just below the vectors at the top of the first 32 KB: $00:FFC0, file offset $7FC0 in LoROM.",
    ),
    h(
        "header_hirom",
        "rom",
        2,
        "At which file offset is a HiROM game's internal header?",
        0xFFC0,
        "In HiROM the first bank is a whole 64 KB, so the header at $00:FFC0 is file offset $FFC0.",
    ),
    h(
        "reset_vector",
        "reset",
        2,
        "At which address in bank $00 is the reset vector?",
        0xFFFC,
        "The CPU starts in emulation mode and reads where to start from $FFFC–$FFFD.",
    ),
    h(
        "nmi_vector",
        "nmi",
        2,
        "At which address in bank $00 is the native-mode NMI vector?",
        0xFFEA,
        "In native mode the NMI handler's address is read from $FFEA–$FFEB.",
    ),
    h(
        "irq_vector",
        "irq",
        2,
        "At which address in bank $00 is the native-mode IRQ vector?",
        0xFFEE,
        "In native mode the IRQ handler's address is read from $FFEE–$FFEF.",
    ),
    // Graphics.
    n(
        "tile_size",
        "tiles",
        1,
        "How many pixels wide is a standard tile?",
        8,
        "Tiles are 8×8 pixels; bigger sprites and background tiles are built from them.",
    ),
    n(
        "tile_2bpp",
        "tiles",
        2,
        "How many bytes is one 8×8 tile at 2 bits per pixel?",
        16,
        "64 pixels × 2 bits = 128 bits, 16 bytes.",
    ),
    n(
        "tile_4bpp",
        "tiles",
        2,
        "How many bytes is one 8×8 tile at 4 bits per pixel?",
        32,
        "64 pixels × 4 bits = 256 bits, 32 bytes.",
    ),
    n(
        "tile_8bpp",
        "tiles",
        2,
        "How many bytes is one 8×8 tile at 8 bits per pixel?",
        64,
        "64 pixels × 8 bits, 64 bytes.",
    ),
    n(
        "colours",
        "palettes",
        1,
        "How many colours does CGRAM hold at once?",
        256,
        "CGRAM holds 256 colours; each tile picks from a palette of them.",
    ),
    n(
        "cgram_bytes",
        "palettes",
        2,
        "How many bytes is CGRAM?",
        512,
        "256 colours of two bytes each.",
    ),
    n(
        "colour_bits",
        "palettes",
        2,
        "How many bits make one SNES colour?",
        15,
        "Five bits each of blue, green and red, in a 16-bit word whose top bit is unused.",
    ),
    n(
        "vram_kb",
        "vram",
        2,
        "How many kilobytes is VRAM?",
        64,
        "VRAM is 64 KB, 32K words of 16 bits, shared by tiles and tilemaps.",
    ),
    n(
        "bg_layers",
        "backgrounds",
        1,
        "At most how many background layers can the PPU draw?",
        4,
        "Mode 0 has four layers, BG1 to BG4; the other modes have fewer, with more colours.",
    ),
    n(
        "bg_modes",
        "bg_modes",
        1,
        "How many background modes does the PPU have?",
        8,
        "Modes 0 to 7, set in BGMODE, trade layers for colours; mode 7 is the one that rotates.",
    ),
    n(
        "mode7_layers",
        "mode7",
        1,
        "How many background layers does mode 7 draw?",
        1,
        "Mode 7 draws one large background, rotated and scaled.",
    ),
    n(
        "mode7_map",
        "mode7",
        2,
        "How many tiles wide is the mode 7 map?",
        128,
        "The mode 7 map is 128 × 128 tiles of 8 × 8 pixels: 1024 pixels each way.",
    ),
    n(
        "sprites",
        "sprites",
        1,
        "How many sprites can the PPU keep track of at once?",
        128,
        "OAM has room for 128 sprites.",
    ),
    n(
        "sprites_line",
        "sprites",
        2,
        "At most how many sprites can appear on one line?",
        32,
        "Past 32 sprites on a line (or 34 slivers of tiles) the PPU drops the rest.",
    ),
    n(
        "oam_bytes",
        "oam",
        2,
        "How many bytes is OAM?",
        544,
        "512 bytes of four per sprite, and a 32-byte table of each sprite's X bit 8 and size.",
    ),
    n(
        "oam_entry",
        "oam",
        2,
        "How many bytes of OAM's main table describe one sprite?",
        4,
        "X, Y, the tile, and a byte of palette, priority, flips and the tile's top bit.",
    ),
    // Timing.
    n(
        "fps",
        "frame",
        1,
        "About how many frames a second does an NTSC SNES draw?",
        60,
        "NTSC is 60 frames a second (PAL 50).",
    ),
    n(
        "lines",
        "frame",
        2,
        "How many lines does an NTSC frame have, the unseen ones included?",
        262,
        "262 lines, of which 224 are normally shown.",
    ),
    n(
        "visible",
        "frame",
        2,
        "How many lines of an NTSC frame are normally shown?",
        224,
        "224 lines, or 239 with overscan.",
    ),
    n(
        "vblank_start",
        "vblank",
        2,
        "On which line does vertical blank start, with a 224-line picture?",
        225,
        "Lines 0 to 224 draw (0 is blank); vertical blank runs from 225 to the frame's end.",
    ),
    n(
        "dma_channels",
        "dma",
        1,
        "How many DMA channels does the CPU have?",
        8,
        "Eight channels, set up at $43x0 and started together by MDMAEN.",
    ),
    n(
        "dma_cycles",
        "dma",
        2,
        "How many master cycles does DMA take for each byte?",
        8,
        "About eight master cycles a byte, plus a little to start each channel.",
    ),
    n(
        "hdma_channels",
        "hdma",
        1,
        "How many channels can HDMA use?",
        8,
        "HDMA uses the same eight channels as DMA; HDMAEN picks which.",
    ),
    n(
        "dots",
        "frame",
        2,
        "How many dots wide is one line, the unseen ones included?",
        341,
        "341 dots, of which 256 are drawn; the rest is horizontal blank.",
    ),
    n(
        "master_line",
        "frame",
        5,
        "How many master cycles does one line take?",
        1364,
        "341 dots of 4 master cycles each.",
    ),
    // The CPU.
    n(
        "p_m",
        "widths",
        2,
        "Which bit of P is M, the accumulator's width?",
        5,
        "M is bit 5: set, A is 8 bits; clear, 16. `SEP #$20` sets it, `REP #$20` clears it.",
    ),
    n(
        "p_x",
        "widths",
        2,
        "Which bit of P is X, the index registers' width?",
        4,
        "X is bit 4: set, X and Y are 8 bits. `SEP #$10` and `REP #$10` change it.",
    ),
    n(
        "p_c",
        "flags_branches",
        2,
        "Which bit of P is the carry flag?",
        0,
        "C is bit 0; `BCC` and `BCS` test it, and `CMP` sets it when A is at least the operand.",
    ),
    n(
        "p_z",
        "flags_branches",
        2,
        "Which bit of P is the zero flag?",
        1,
        "Z is bit 1; `BEQ` and `BNE` test it.",
    ),
    n(
        "p_n",
        "flags_branches",
        2,
        "Which bit of P is the negative flag?",
        7,
        "N is bit 7, a copy of the result's top bit; `BMI` and `BPL` test it.",
    ),
    n(
        "dp_bytes",
        "addressing",
        2,
        "How many bytes can a direct-page address reach from D?",
        256,
        "A direct-page operand is one byte, added to D: 256 bytes, which are shorter and quicker to reach.",
    ),
    n(
        "stack_bank",
        "stack",
        2,
        "In which bank is the stack?",
        0,
        "The stack pointer is 16 bits and always in bank $00.",
    ),
    n(
        "joypad_buttons",
        "joypads",
        1,
        "How many buttons does a standard controller have, the D-pad's four included?",
        12,
        "B, Y, Select, Start, the four directions, A, X, L and R.",
    ),
    n(
        "mul_bits",
        "math_hw",
        1,
        "How many bits are the two numbers the CPU's multiplier takes?",
        8,
        "WRMPYA × WRMPYB: 8 bits by 8, a 16-bit product.",
    ),
    n(
        "div_bits",
        "math_hw",
        2,
        "How many bits is the dividend the CPU's divider takes?",
        16,
        "WRDIVL–WRDIVH ÷ WRDIVB: 16 bits by 8, a 16-bit quotient and remainder.",
    ),
    // Sound.
    n(
        "ipl_bytes",
        "spc700",
        2,
        "How many bytes is the SPC700's boot ROM, the IPL?",
        64,
        "64 bytes at $FFC0: just enough to take the sound driver through the ports.",
    ),
    n(
        "apu_ports",
        "apu_ports",
        1,
        "How many ports connect the CPU and the sound CPU?",
        4,
        "$2140–$2143 on the CPU's side, $F4–$F7 on the SPC700's.",
    ),
    n(
        "voices",
        "dsp",
        1,
        "How many voices can the S-DSP play at once?",
        8,
        "Eight voices, each playing a BRR sample at its own pitch and volume.",
    ),
    n(
        "dsp_rate",
        "dsp",
        2,
        "At how many samples a second does the S-DSP output sound?",
        32000,
        "32 kHz stereo.",
    ),
    n(
        "brr_block",
        "brr",
        2,
        "How many bytes is one BRR block?",
        9,
        "A header byte, then eight bytes of sixteen 4-bit samples.",
    ),
    n(
        "brr_samples",
        "brr",
        2,
        "How many samples does one BRR block hold?",
        16,
        "Sixteen 4-bit samples, each shifted and filtered as the header says.",
    ),
];

/// A statement: the prompt, the right answer and wrong ones.
pub struct Said {
    pub id: &'static str,
    pub concept: &'static str,
    pub level: u8,
    pub prompt: &'static str,
    pub answer: &'static str,
    pub wrong: &'static [&'static str],
    pub explain: &'static str,
}

const fn s(
    id: &'static str,
    concept: &'static str,
    level: u8,
    prompt: &'static str,
    answer: &'static str,
    wrong: &'static [&'static str],
    explain: &'static str,
) -> Said {
    Said {
        id,
        concept,
        level,
        prompt,
        answer,
        wrong,
        explain,
    }
}

pub const SAIDS: &[Said] = &[
    // The machine.
    s(
        "cpu_runs",
        "cpu",
        1,
        "Which chip runs the game's program?",
        "The CPU, the 5A22",
        &["The PPU", "The S-DSP", "The cartridge's ROM"],
        "The 5A22 runs the game's code; the PPU draws and the APU plays sound, each set up by the CPU.",
    ),
    s(
        "cpu_extras",
        "cpu",
        2,
        "What does the 5A22 add to its 65C816 core?",
        "DMA, multiply and divide, timers and joypad reading",
        &[
            "The background layers",
            "The sound samples",
            "A second 65C816",
        ],
        "Nintendo's CPU is a 65C816 with DMA, multiply and divide, the H/V timers and the joypad port built in.",
    ),
    s(
        "cpu_speed",
        "cpu",
        2,
        "Why does the CPU's speed change as it runs?",
        "Some memory is read at 3.58 MHz and some slower",
        &[
            "It slows down when the screen is busy",
            "The sound CPU borrows its cycles",
            "It speeds up in vertical blank",
        ],
        "Each access takes 6, 8 or 12 master cycles depending on what is read: fast ROM and registers are quicker than WRAM or slow ROM.",
    ),
    s(
        "ppu_draws",
        "ppu",
        1,
        "What does the PPU do?",
        "Draws the picture from VRAM, OAM and CGRAM",
        &[
            "Runs the game's code",
            "Mixes the sound",
            "Reads the controllers",
        ],
        "The PPU draws each line from its own memories; the CPU only sets it up.",
    ),
    s(
        "ppu_chips",
        "ppu",
        2,
        "How does the CPU reach the PPU's memories?",
        "Through the PPU's registers at $2100–$213F",
        &[
            "By reading VRAM at $7E:0000",
            "Through the sound ports",
            "It can't; only DMA can",
        ],
        "VRAM, OAM and CGRAM are the PPU's own; the CPU (or DMA) writes them through ports such as VMDATA.",
    ),
    s(
        "apu_plays",
        "apu",
        1,
        "What does the APU do?",
        "Plays the sound, with its own CPU and memory",
        &[
            "Draws the sprites",
            "Copies graphics to VRAM",
            "Checks the cartridge",
        ],
        "The APU is a small computer of its own: the SPC700, the S-DSP and 64 KB of ARAM.",
    ),
    s(
        "apu_alone",
        "apu",
        2,
        "How does the main CPU reach the APU?",
        "Only through four ports, $2140–$2143",
        &[
            "By writing ARAM directly",
            "Through VRAM",
            "With DMA to the S-DSP",
        ],
        "The CPU can't see ARAM; it passes bytes through the ports, and the SPC700 does the rest.",
    ),
    s(
        "map_is",
        "memory_map",
        1,
        "What is a memory map?",
        "Which addresses reach which memory or hardware",
        &[
            "A picture of the game's levels",
            "The list of the game's routines",
            "Where tiles sit in VRAM",
        ],
        "The same address space holds ROM, WRAM and the hardware's registers; the map says which is where.",
    ),
    s(
        "map_wram",
        "memory_map",
        2,
        "Which banks hold all of WRAM?",
        "$7E and $7F",
        &["$00 to $3F", "$80 to $BF", "$C0 to $FF"],
        "WRAM is 128 KB at $7E:0000–$7F:FFFF; its first 8 KB also shows low in the system banks.",
    ),
    s(
        "map_regs",
        "memory_map",
        2,
        "Where are the PPU's registers in the address space?",
        "$2100–$213F in banks $00–$3F and $80–$BF",
        &["$7E:2100", "$C0:0000–$C0:00FF", "Only in bank $00 at $F000"],
        "The system banks carry WRAM's first 8 KB, the registers and ROM; the PPU's registers are at $21xx.",
    ),
    s(
        "rom_holds",
        "rom",
        1,
        "What does the cartridge's ROM hold?",
        "The game's code and data",
        &[
            "The saved games",
            "What the PPU is drawing now",
            "The sound CPU's memory",
        ],
        "Code, graphics, music, maps: everything the game ships with. Saves go in SRAM.",
    ),
    s(
        "rom_header",
        "rom",
        2,
        "What does a game's internal header hold?",
        "Its title, mapping, sizes and region",
        &[
            "Its compressed graphics",
            "The player's saves",
            "The sound driver",
        ],
        "The header, just below the vectors, names the game and says how the cartridge is wired.",
    ),
    s(
        "mapping_is",
        "mapping",
        1,
        "What do LoROM and HiROM describe?",
        "How the ROM appears at the CPU's addresses",
        &[
            "The size of the save RAM",
            "The TV standard",
            "The graphics mode",
        ],
        "The cartridge's wiring decides which addresses reach which part of the ROM.",
    ),
    s(
        "mapping_lo",
        "mapping",
        2,
        "Where does LoROM put the ROM in each bank?",
        "In the upper half, $8000–$FFFF",
        &[
            "In the lower half, $0000–$7FFF",
            "Across the whole bank",
            "Only in bank $00",
        ],
        "The lower half of the system banks has WRAM and registers, so LoROM uses the upper half.",
    ),
    s(
        "wram_for",
        "wram",
        1,
        "What is WRAM for?",
        "The game's variables and buffers",
        &[
            "The tiles the PPU draws",
            "The sound samples",
            "The palette",
        ],
        "WRAM is the CPU's own RAM: variables, the stack, and buffers copied to VRAM by DMA.",
    ),
    s(
        "regs_how",
        "hw_registers",
        1,
        "How does the CPU tell the PPU what to do?",
        "By writing its registers at $21xx",
        &[
            "By calling its routines",
            "By sending it messages over $2140",
            "It can't; the PPU reads the ROM itself",
        ],
        "Each register is an address that goes to hardware, not memory: a write there changes what the PPU does.",
    ),
    s(
        "regs_read",
        "hw_registers",
        2,
        "What happens if a game reads most PPU registers back?",
        "It gets nothing useful: they are write-only",
        &[
            "It gets the last value written",
            "The PPU resets",
            "It reads the ROM underneath",
        ],
        "So games keep copies of what they wrote in WRAM (shadow registers).",
    ),
    // Graphics.
    s(
        "tile_is",
        "tiles",
        1,
        "What is a tile?",
        "An 8×8 block of pixels, each a colour number",
        &[
            "One sprite's position",
            "A full-colour 16×16 picture",
            "A row of a tilemap",
        ],
        "Pixels in a tile are numbers into a palette, so the same tile can be drawn in different colours.",
    ),
    s(
        "palette_is",
        "palettes",
        1,
        "What does a tile's palette do?",
        "Turns its pixel numbers into colours",
        &["Sets its position", "Flips it", "Chooses its size"],
        "A 4bpp tile's pixels are 0–15; its palette says which of CGRAM's colours they are, and 0 is see-through.",
    ),
    s(
        "vram_holds",
        "vram",
        1,
        "What does VRAM hold?",
        "Tiles and tilemaps",
        &["The palette", "The sprite table", "The game's variables"],
        "VRAM is the PPU's memory for the tiles and the maps of backgrounds; colours are in CGRAM, sprites in OAM.",
    ),
    s(
        "vram_when",
        "vram",
        2,
        "When can the CPU safely write VRAM?",
        "In vertical blank or forced blank",
        &[
            "Any time",
            "Only while a line is drawn",
            "Only during the NMI's first instruction",
        ],
        "While the PPU draws, it owns VRAM; writes are lost outside vertical or forced blank.",
    ),
    s(
        "bg_is",
        "backgrounds",
        1,
        "What is a background layer?",
        "A grid of tiles drawn behind or among the sprites",
        &[
            "A single large picture in ROM",
            "The sprites' shadow",
            "The colour behind the palette",
        ],
        "Each layer is a tilemap of tiles, scrolled as a whole.",
    ),
    s(
        "bg_regs",
        "backgrounds",
        2,
        "Which register turns background layers on for the main screen?",
        "TM",
        &["BGMODE", "INIDISP", "OBSEL"],
        "TM ($212C) has a bit per layer and one for sprites; BGMODE only says what the layers are.",
    ),
    s(
        "map_cell",
        "tilemaps",
        1,
        "What does a tilemap's entry say?",
        "Which tile, palette and flips go in that cell",
        &[
            "The colour of that pixel",
            "Where a sprite goes",
            "The layer's scroll",
        ],
        "Each 16-bit entry has a tile number, a palette, a priority bit and flips.",
    ),
    s(
        "map_size",
        "tilemaps",
        2,
        "How many tiles is one tilemap screen?",
        "32 × 32",
        &["16 × 16", "64 × 64", "256 × 224"],
        "One screen of map is 32 × 32 entries, 2 KB; a layer can be up to 2 × 2 screens.",
    ),
    s(
        "modes_trade",
        "bg_modes",
        2,
        "What does a higher colour depth cost in the background modes?",
        "Fewer layers",
        &["Fewer sprites", "Slower scrolling", "A smaller screen"],
        "Mode 0 has four 2bpp layers; mode 1 two of 4bpp and one of 2bpp; mode 3 one of 8bpp and one of 4bpp.",
    ),
    s(
        "sprite_is",
        "sprites",
        1,
        "What is a sprite?",
        "A small picture the PPU draws anywhere on screen",
        &["A background layer", "A colour in CGRAM", "A sound effect"],
        "Sprites (objects) are placed by their own X and Y, not by a map.",
    ),
    s(
        "oam_holds",
        "oam",
        1,
        "What does OAM hold?",
        "Each sprite's position, tile, palette and priority",
        &[
            "The sprites' pixels",
            "The sprites' colours",
            "The sprites' code",
        ],
        "OAM describes the sprites; their pixels are tiles in VRAM and their colours in CGRAM.",
    ),
    s(
        "scroll_is",
        "scrolling",
        1,
        "What does scrolling a background change?",
        "Which part of its map shows on screen",
        &[
            "The tiles' colours",
            "The tilemap in VRAM",
            "The layer's depth",
        ],
        "The scroll registers move the window onto the map; nothing in VRAM moves.",
    ),
    s(
        "scroll_twice",
        "scrolling",
        2,
        "How is BG1HOFS written?",
        "Twice, low byte then high",
        &[
            "Once, 8 bits",
            "Through DMA only",
            "Once, 16 bits at $210D–$210E",
        ],
        "The scroll registers take two writes each to one address, making a 10-bit value.",
    ),
    s(
        "m7_does",
        "mode7",
        1,
        "What can mode 7 do that the other modes can't?",
        "Rotate and scale its background",
        &["Draw more sprites", "Use 4 background layers", "Play sound"],
        "A matrix (M7A–M7D) turns and stretches the one layer, and HDMA can change it each line for a floor in perspective.",
    ),
    s(
        "cmath_is",
        "color_math",
        1,
        "What does colour math do?",
        "Adds or subtracts one screen's colours from another's",
        &[
            "Mixes the palettes in CGRAM",
            "Makes more colours in a tile",
            "Speeds up the PPU",
        ],
        "The main and sub screens are added or subtracted per pixel, for see-through water and shadows.",
    ),
    s(
        "cmath_regs",
        "color_math",
        2,
        "Which register says which layers colour math affects?",
        "CGADSUB",
        &["CGWSEL", "COLDATA", "TM"],
        "CGADSUB ($2131) picks add or subtract, halving, and the layers it applies to; CGWSEL says where and against what.",
    ),
    s(
        "compress_why",
        "compression",
        1,
        "Why do games compress graphics in ROM?",
        "To fit more in the cartridge",
        &[
            "Because VRAM only takes compressed data",
            "So the PPU draws faster",
            "To stop them being copied",
        ],
        "ROM was expensive; the CPU unpacks the data before it reaches VRAM.",
    ),
    s(
        "compress_who",
        "compression",
        2,
        "What unpacks compressed graphics?",
        "The game's own code, on the CPU",
        &[
            "The PPU, as it draws",
            "DMA, on the way to VRAM",
            "The S-DSP",
        ],
        "Neither the PPU nor DMA can unpack; the CPU does, into WRAM or straight into VRAM.",
    ),
    s(
        "compress_ppu",
        "compression",
        2,
        "Why can't a game send compressed tiles straight to VRAM for the PPU?",
        "The PPU only reads tiles unpacked",
        &[
            "DMA is too slow",
            "VRAM can't be written by DMA",
            "The PPU rejects any data from ROM",
        ],
        "The PPU reads tile bits as they are; unpacking is the game's job.",
    ),
    s(
        "compress_where",
        "compression",
        2,
        "Where do unpacked graphics usually go before VRAM?",
        "A buffer in WRAM, then DMA to VRAM",
        &["Straight to CGRAM", "Into SRAM", "Into ARAM"],
        "Unpacking into WRAM lets the game copy the result with DMA in vertical blank.",
    ),
    // Timing.
    s(
        "frame_is",
        "frame",
        1,
        "What is a frame?",
        "One whole picture, drawn line by line from the top",
        &[
            "One tile",
            "One second of the game",
            "One sprite's animation",
        ],
        "The PPU draws 60 frames a second, each 262 lines, most of them seen.",
    ),
    s(
        "vblank_why",
        "vblank",
        1,
        "Why do games update VRAM in vertical blank?",
        "The PPU isn't drawing then",
        &[
            "The CPU is faster then",
            "DMA only works then",
            "The sound CPU is idle then",
        ],
        "Between frames nothing is drawn, so VRAM, OAM and CGRAM can be written.",
    ),
    s(
        "fblank_is",
        "forced_blank",
        1,
        "What does forced blank do?",
        "Blacks out the screen so VRAM can be written any time",
        &["Pauses the CPU", "Mutes the sound", "Clears VRAM"],
        "Bit 7 of INIDISP: games set it while loading a whole scene.",
    ),
    s(
        "fblank_when",
        "forced_blank",
        2,
        "When do games usually turn forced blank on?",
        "While loading a new screen's graphics",
        &[
            "Every frame in the NMI",
            "Only when the game crashes",
            "When a sound plays",
        ],
        "With the screen off there is no hurry: the whole of VRAM can be filled at once.",
    ),
    s(
        "fblank_bits",
        "forced_blank",
        2,
        "What else does INIDISP set besides forced blank?",
        "The screen's brightness",
        &["The background mode", "The sprite size", "The scroll"],
        "Bits 0–3 of INIDISP are the brightness, 0 to 15.",
    ),
    s(
        "nmi_when",
        "nmi",
        1,
        "When does the NMI fire, when it is on?",
        "At the start of vertical blank",
        &[
            "At the end of every line",
            "When a button is pressed",
            "When DMA finishes",
        ],
        "The NMI is the frame's heartbeat: games do their VRAM and OAM updates in its handler.",
    ),
    s(
        "nmi_on",
        "nmi",
        2,
        "Which bit turns the NMI on?",
        "Bit 7 of NMITIMEN",
        &["Bit 7 of INIDISP", "Bit 0 of RDNMI", "The I flag"],
        "NMITIMEN ($4200) bit 7; the I flag can't hold it off, but NMITIMEN can.",
    ),
    s(
        "irq_for",
        "irq",
        1,
        "What is the timer IRQ for?",
        "Running code at a chosen line, for changes mid-screen",
        &["Counting frames", "Reading the controllers", "Starting DMA"],
        "Set HTIMEL/VTIMEL and NMITIMEN, and the CPU is interrupted at that point of the picture.",
    ),
    s(
        "irq_ack",
        "irq",
        2,
        "How does an IRQ handler acknowledge the timer?",
        "By reading TIMEUP",
        &[
            "By writing NMITIMEN",
            "By executing RTI only",
            "By reading RDNMI",
        ],
        "Reading TIMEUP ($4211) clears the IRQ flag, or the handler runs again at once.",
    ),
    s(
        "dma_does",
        "dma",
        1,
        "What does DMA do?",
        "Copies bytes between memory and a B-bus register while the CPU waits",
        &["Draws sprites", "Decompresses graphics", "Plays sound"],
        "DMA is how games fill VRAM, CGRAM and OAM quickly.",
    ),
    s(
        "dma_start",
        "dma",
        2,
        "How does a game start DMA?",
        "By writing the channels' bits to MDMAEN",
        &[
            "By writing BBAD",
            "By reading VMDATA",
            "By setting forced blank",
        ],
        "Each channel is set up at $43x0–$43x6, then a write to MDMAEN ($420B) starts them in order.",
    ),
    s(
        "hdma_for",
        "hdma",
        1,
        "What is HDMA used for?",
        "Changing PPU registers line by line",
        &[
            "Copying whole screens",
            "Loading music",
            "Reading the controllers",
        ],
        "At the end of each line it writes a few bytes from a table: gradients, waves, mode 7 floors.",
    ),
    s(
        "hdma_start",
        "hdma",
        2,
        "Which register turns HDMA channels on for the frame?",
        "HDMAEN",
        &["MDMAEN", "NMITIMEN", "DMAP0"],
        "HDMAEN ($420C); it is usually written in vertical blank.",
    ),
    s(
        "loop_does",
        "main_loop",
        1,
        "What does a typical main loop do?",
        "Runs the game's logic, then waits for the next frame",
        &[
            "Draws every pixel itself",
            "Plays the music note by note",
            "Copies the whole ROM to WRAM",
        ],
        "One pass a frame: read input, move things, then wait for the NMI.",
    ),
    s(
        "loop_waits",
        "main_loop",
        2,
        "How does a main loop usually wait for the next frame?",
        "It loops until the NMI handler sets a flag",
        &[
            "It counts cycles",
            "It executes STP",
            "It waits for a button",
        ],
        "The NMI handler sets a flag in WRAM; the main loop spins on it, then clears it and goes on.",
    ),
    s(
        "loop_wai",
        "main_loop",
        2,
        "Which instruction can wait for the next interrupt without spinning?",
        "WAI",
        &["STP", "NOP", "BRK"],
        "`WAI` stops the CPU until an interrupt; `STP` stops it for good.",
    ),
    s(
        "shadow_why",
        "shadows",
        1,
        "Why keep a copy of a register in WRAM?",
        "The register can't be read back",
        &[
            "WRAM is faster than the register",
            "The PPU reads WRAM",
            "To save ROM",
        ],
        "A shadow copy lets code change one bit and know the rest.",
    ),
    s(
        "shadow_when",
        "shadows",
        2,
        "When is a shadow register usually copied to the hardware?",
        "In the NMI handler, in vertical blank",
        &[
            "At reset only",
            "On every write to it",
            "Never; the PPU reads it",
        ],
        "The main loop changes the copy; the NMI handler writes it out once a frame.",
    ),
    s(
        "shadow_scroll",
        "shadows",
        2,
        "Why do games keep the scroll in WRAM too?",
        "The scroll registers can't be read back, and take two writes each",
        &[
            "They are faster to read than ROM",
            "The PPU reads them from WRAM",
            "DMA needs them there",
        ],
        "The game adds to its own copy each frame and writes both bytes out in vertical blank.",
    ),
    s(
        "shadow_where",
        "shadows",
        2,
        "Where do shadow registers live?",
        "In WRAM, usually the direct page or the first 8 KB",
        &["In VRAM", "In the cartridge's ROM", "In ARAM"],
        "Low WRAM is quick to reach from any bank.",
    ),
    // The CPU.
    s(
        "asm_is",
        "assembly",
        1,
        "What is assembly language?",
        "The CPU's instructions written as mnemonics",
        &[
            "The C a game was written in",
            "The PPU's settings",
            "A compressed format",
        ],
        "Each line is one instruction, such as `LDA $12`, that the assembler turns into bytes.",
    ),
    s(
        "regs_a",
        "cpu_registers",
        1,
        "Which register does most of the 65816's arithmetic?",
        "The accumulator, A",
        &["X", "The stack pointer", "The data bank register"],
        "A takes the result of ADC, SBC, AND and the rest; X and Y are for counting and indexing.",
    ),
    s(
        "regs_d",
        "cpu_registers",
        2,
        "What does the D register hold?",
        "The base of the direct page",
        &["The data bank", "The stack's top", "The decimal flag"],
        "Direct-page addresses are added to D, anywhere in bank $00.",
    ),
    s(
        "widths_are",
        "widths",
        1,
        "What do the M and X flags change?",
        "Whether A and X/Y are 8 or 16 bits",
        &[
            "Which bank code runs in",
            "Whether interrupts are on",
            "The stack's size",
        ],
        "The same bytes decode differently at each width, which is why disassemblers track them.",
    ),
    s(
        "modes_are",
        "addressing",
        1,
        "What does an addressing mode say?",
        "Where an instruction finds its operand",
        &[
            "Which bank it runs in",
            "How many cycles it takes",
            "Whether it can be interrupted",
        ],
        "`LDA #$12` loads the number; `LDA $12` loads from address $12.",
    ),
    s(
        "banks_dbr",
        "banks",
        2,
        "Which bank does `LDA $1234` read from?",
        "The data bank, DBR",
        &["Always bank $00", "The program bank", "Bank $7E"],
        "An absolute address takes its bank from DBR; set it with `PLB`.",
    ),
    s(
        "banks_long",
        "banks",
        2,
        "How does code reach another bank without changing DBR?",
        "With a long address, such as `LDA $7E1234`",
        &["It can't", "With `REP`", "Through the stack"],
        "Long (24-bit) addressing names the bank in the operand.",
    ),
    s(
        "stack_jsr",
        "stack",
        1,
        "What does JSR push on the stack?",
        "The return address",
        &["The accumulator", "The flags", "The target address"],
        "JSR pushes where to come back to; RTS pulls it.",
    ),
    s(
        "branch_by",
        "flags_branches",
        1,
        "What decides whether a branch is taken?",
        "The flags, set by an earlier instruction",
        &[
            "The accumulator's value itself",
            "The stack",
            "The program bank",
        ],
        "`CMP` sets the flags; `BEQ`, `BCC` and the rest test them.",
    ),
    s(
        "jt_is",
        "jump_tables",
        1,
        "What is a jump table?",
        "A list of routine addresses, picked by an index",
        &[
            "A table of branch offsets in the header",
            "The interrupt vectors",
            "A list of labels in the assembler",
        ],
        "`JMP ($8000,X)` jumps to the X-th address of the table: a switch statement.",
    ),
    s(
        "reset_runs",
        "reset",
        1,
        "What runs when the console is switched on?",
        "The routine the reset vector points at",
        &[
            "The NMI handler",
            "The first byte of the ROM",
            "The sound driver",
        ],
        "The CPU reads $FFFC–$FFFD and starts there, in emulation mode.",
    ),
    s(
        "reset_mode",
        "reset",
        2,
        "What mode is the 65816 in after reset?",
        "Emulation mode, 8 bits like a 6502",
        &["Native mode, 16 bits", "Decimal mode", "Mode 7"],
        "Games switch to native mode with `CLC` then `XCE` early in the reset code.",
    ),
    s(
        "reset_first",
        "reset",
        2,
        "What does a reset routine usually do first?",
        "Turn off interrupts and set the CPU up",
        &[
            "Play the title music",
            "Draw the logo",
            "Read the controllers",
        ],
        "`SEI`, `CLC; XCE`, the stack and the registers, then forced blank while it clears memory.",
    ),
    s(
        "math_why",
        "math_hw",
        1,
        "Why do games use the hardware multiplier?",
        "The 65816 has no multiply instruction",
        &[
            "It is more accurate",
            "The PPU needs it",
            "It works in decimal",
        ],
        "Multiplying by shifting and adding takes many instructions; the hardware does it in a few cycles.",
    ),
    s(
        "math_wait",
        "math_hw",
        2,
        "What must code do after writing WRMPYB?",
        "Wait a few cycles before reading RDMPYL",
        &[
            "Write NMITIMEN",
            "Start DMA",
            "Nothing: the result is there at once",
        ],
        "The product takes 8 CPU cycles; reading too soon gets a partial result.",
    ),
    s(
        "pad_how",
        "joypads",
        1,
        "How do most games read the controllers?",
        "From JOY1L–JOY4H, filled automatically each frame",
        &["By polling the APU ports", "From VRAM", "Through DMA"],
        "With auto-read on (NMITIMEN bit 0), the buttons are read at the start of vertical blank.",
    ),
    s(
        "pad_wait",
        "joypads",
        2,
        "What should code check before reading JOY1L?",
        "That the auto-read has finished (HVBJOY bit 0)",
        &["That forced blank is on", "That the NMI is off", "Nothing"],
        "The auto-read takes about three lines; HVBJOY bit 0 is set while it runs.",
    ),
    s(
        "obj_is",
        "objects",
        1,
        "What is a game object in code?",
        "A record in WRAM for one thing: its position, state and routine",
        &["A sprite in OAM", "A tile in VRAM", "A sound effect"],
        "Objects are the game's actors; each frame the game runs each one and draws it as sprites.",
    ),
    s(
        "obj_run",
        "objects",
        2,
        "How do games often run each object's code?",
        "Through a table of routines, one per kind of object",
        &[
            "With one routine for all",
            "Through the NMI vector",
            "With the APU's help",
        ],
        "The object's type indexes a jump table: `JSR ($8000,X)`.",
    ),
    s(
        "obj_slots",
        "objects",
        2,
        "How do games usually keep many objects?",
        "In a table of fixed-size slots in WRAM",
        &[
            "As routines in ROM, one per object",
            "In OAM only",
            "In VRAM, beside their tiles",
        ],
        "Each slot holds one object's fields; an empty slot is free for the next thing spawned.",
    ),
    s(
        "obj_draw",
        "objects",
        2,
        "How does an object usually get on screen?",
        "The game writes its sprites to an OAM copy in WRAM, sent by DMA",
        &[
            "The PPU reads the object's record",
            "It is drawn into VRAM pixel by pixel",
            "Through HDMA",
        ],
        "A 544-byte buffer in WRAM is filled each frame and copied to OAM in vertical blank.",
    ),
    // Sound.
    s(
        "spc_runs",
        "spc700",
        1,
        "What runs the sound driver?",
        "The SPC700, the APU's own CPU",
        &["The main CPU", "The PPU", "The S-DSP"],
        "The SPC700 runs the driver from ARAM and tells the S-DSP what to play.",
    ),
    s(
        "spc_where",
        "spc700",
        2,
        "Where does the SPC700 run its code from?",
        "Its own 64 KB of ARAM",
        &["The cartridge's ROM", "WRAM", "VRAM"],
        "Everything the sound CPU runs was uploaded into ARAM through the ports.",
    ),
    s(
        "spc_boot",
        "spc700",
        2,
        "What does the SPC700 run at power-on?",
        "The IPL boot ROM, which waits for an upload",
        &[
            "The game's sound driver from ROM",
            "Nothing until reset",
            "A test tone",
        ],
        "The 64-byte IPL signals $AA/$BB on the ports and takes bytes the CPU sends.",
    ),
    s(
        "ports_upload",
        "apu_ports",
        2,
        "How does a game get its sound driver into ARAM?",
        "It sends it through the ports to the IPL",
        &[
            "By DMA to ARAM",
            "The APU reads it from ROM",
            "It writes ARAM at $7F:0000",
        ],
        "A handshake on $2140–$2141 moves each byte while both CPUs agree on a counter.",
    ),
    s(
        "dsp_does",
        "dsp",
        1,
        "What does the S-DSP do?",
        "Mixes the voices' samples into the sound",
        &[
            "Runs the sound driver",
            "Decompresses graphics",
            "Reads the ports",
        ],
        "It plays BRR samples at a pitch, shapes each with an envelope, and adds echo.",
    ),
    s(
        "dsp_reached",
        "dsp",
        2,
        "How does the SPC700 set the S-DSP's registers?",
        "Through $F2 (the register) and $F3 (the value)",
        &["Directly at $4C", "Through the APU ports", "With DMA"],
        "The S-DSP has 128 registers reached through that pair of addresses.",
    ),
    s(
        "brr_header",
        "brr",
        2,
        "What does a BRR block's header byte hold?",
        "The shift, the filter, and the loop and end flags",
        &["The sample's pitch", "The voice it plays on", "The volume"],
        "Bits 4–7 are the shift, 2–3 the filter, bit 1 loop and bit 0 end.",
    ),
    s(
        "brr_is",
        "brr",
        1,
        "What is BRR?",
        "The S-DSP's compressed sample format",
        &["A kind of reverb", "A background mode", "The sound driver"],
        "Bit Rate Reduction: 9 bytes for 16 samples.",
    ),
    s(
        "driver_does",
        "sound_driver",
        1,
        "What does a sound driver do?",
        "Plays music and effects from commands the game sends",
        &[
            "Draws the sound's waveform",
            "Converts BRR to WAV",
            "Checks the cartridge",
        ],
        "It reads the song's data and sets the S-DSP each tick.",
    ),
    s(
        "driver_told",
        "sound_driver",
        2,
        "How does the game ask the driver to play a sound?",
        "It writes a command to the APU ports",
        &[
            "It writes the S-DSP's registers",
            "It jumps into ARAM",
            "It changes INIDISP",
        ],
        "The driver watches the ports; a byte there is a song or an effect to start.",
    ),
    s(
        "driver_ticks",
        "sound_driver",
        2,
        "What keeps a sound driver's music in time?",
        "The SPC700's timers",
        &["The NMI", "The main CPU's loop", "HDMA"],
        "The driver waits on a timer ($FA–$FC and $FD–$FF) and steps the song on each tick.",
    ),
];

/// The hardware registers each concept is about, for level 2.
pub const CONCEPT_REGISTERS: &[(&str, &[&str])] = &[
    ("ppu", &["INIDISP", "BGMODE", "TM"]),
    ("hw_registers", &["INIDISP", "NMITIMEN", "MDMAEN"]),
    ("wram", &["WMDATA", "WMADDL"]),
    ("tiles", &["BG12NBA", "BG34NBA", "OBSEL"]),
    ("palettes", &["CGADD", "CGDATA"]),
    ("vram", &["VMAIN", "VMADDL", "VMDATAL"]),
    ("backgrounds", &["BGMODE", "TM", "BG1SC"]),
    ("tilemaps", &["BG1SC", "BG2SC", "BG3SC"]),
    ("bg_modes", &["BGMODE"]),
    ("sprites", &["OBSEL", "OAMADDL", "OAMDATA"]),
    ("oam", &["OAMADDL", "OAMADDH", "OAMDATA"]),
    ("scrolling", &["BG1HOFS", "BG1VOFS"]),
    ("mode7", &["M7SEL", "M7A", "M7B"]),
    ("color_math", &["CGWSEL", "CGADSUB", "COLDATA"]),
    ("forced_blank", &["INIDISP"]),
    ("vblank", &["RDNMI", "HVBJOY"]),
    ("nmi", &["NMITIMEN", "RDNMI"]),
    ("irq", &["NMITIMEN", "HTIMEL", "VTIMEL", "TIMEUP"]),
    ("dma", &["MDMAEN", "DMAP0", "BBAD0", "A1T0L", "DAS0L"]),
    ("hdma", &["HDMAEN", "DMAP0", "BBAD0"]),
    ("math_hw", &["WRMPYA", "WRMPYB", "RDMPYL", "WRDIVB"]),
    ("joypads", &["NMITIMEN", "HVBJOY", "JOY1L", "JOYSER0"]),
    ("apu_ports", &["APUIO0", "APUIO1", "APUIO2"]),
];

/// The S-DSP registers each sound concept is about.
pub const CONCEPT_DSP: &[(&str, &[&str])] = &[
    ("dsp", &["KON", "KOFF", "FLG", "V0VOLL", "V0PITCHL"]),
    ("brr", &["DIR", "V0SRCN"]),
    ("sound_driver", &["KON", "V0ADSR1"]),
];

/// The instructions each CPU concept is about, for "what does it do".
pub const CONCEPT_MNEMONICS: &[(&str, &[&str])] = &[
    ("assembly", &["LDA", "STA", "ADC", "CMP", "INC"]),
    ("cpu_registers", &["TAX", "TXA", "TAY", "TCD", "XBA"]),
    ("widths", &["REP", "SEP", "XBA"]),
    ("banks", &["PHB", "PLB", "JML", "JSL", "RTL", "PHK"]),
    ("stack", &["PHA", "PLA", "PHP", "PLP", "JSR", "RTS"]),
    (
        "flags_branches",
        &["BEQ", "BNE", "BCC", "BCS", "BMI", "BPL"],
    ),
    ("reset", &["SEI", "CLC", "XCE", "REP"]),
    ("main_loop", &["WAI", "BRA"]),
    ("nmi", &["RTI"]),
];

/// Opcodes whose addressing mode a concept asks about.
pub const CONCEPT_OPCODES: &[(&str, &[u8])] = &[
    // LDA in eight modes.
    (
        "addressing",
        &[0xA9, 0xA5, 0xAD, 0xBD, 0xB5, 0xB2, 0xA7, 0xAF],
    ),
    // JMP and JSR through a table, and plain indirect.
    ("jump_tables", &[0x7C, 0xFC, 0x6C, 0xDC]),
];

/// The glossary's terms each concept is about, for level 1.
pub const CONCEPT_TERMS: &[(&str, &[&str])] = &[
    ("cpu", &["CPU", "65C816"]),
    ("ppu", &["PPU"]),
    ("apu", &["APU", "SPC700"]),
    ("memory_map", &["MMIO", "A-bus", "B-bus"]),
    ("rom", &["ROM", "SRAM"]),
    ("mapping", &["LoROM", "HiROM", "FastROM"]),
    ("wram", &["WRAM", "RAM"]),
    ("hw_registers", &["MMIO", "I/O"]),
    ("tiles", &["BPP"]),
    ("palettes", &["CGRAM"]),
    ("vram", &["VRAM"]),
    ("backgrounds", &["BG"]),
    ("sprites", &["OBJ"]),
    ("oam", &["OAM"]),
    ("mode7", &["Mode 7"]),
    ("frame", &["NTSC", "PAL", "CRT"]),
    ("vblank", &["VBlank", "HBlank"]),
    ("nmi", &["NMI", "ISR"]),
    ("irq", &["IRQ"]),
    ("dma", &["DMA"]),
    ("hdma", &["HDMA"]),
    ("cpu_registers", &["PC", "SP", "DP"]),
    ("banks", &["PBR", "DBR"]),
    ("addressing", &["DP"]),
    ("stack", &["SP"]),
    ("spc700", &["SPC700", "IPL"]),
    ("dsp", &["DSP"]),
    ("brr", &["BRR", "ADSR"]),
    ("flags_branches", &["BCD"]),
];

pub fn number(id: &str) -> Option<&'static Number> {
    NUMBERS.iter().find(|f| f.id == id)
}

pub fn said(id: &str) -> Option<&'static Said> {
    SAIDS.iter().find(|f| f.id == id)
}

pub fn listed<T: Copy>(table: &[(&str, &'static [T])], concept: &str) -> &'static [T] {
    table
        .iter()
        .find(|(c, _)| *c == concept)
        .map_or(&[], |(_, v)| v)
}

#[cfg(test)]
mod tests {
    use super::*;
    use romlens_core::graphics::{oam::OAM_LEN, palette::CGRAM_LEN, render::VRAM_LEN};
    use romlens_core::timing;

    #[test]
    fn numbers_agree_with_the_core() {
        let is = |id: &str, v: u32| assert_eq!(number(id).unwrap().answer, v, "{id}");
        is("oam_bytes", OAM_LEN as u32);
        is("cgram_bytes", CGRAM_LEN as u32);
        is("colours", CGRAM_LEN as u32 / 2);
        is("vram_kb", VRAM_LEN as u32 / 1024);
        is("lines", timing::LINES_NTSC as u32);
        is("visible", timing::VISIBLE as u32);
        is("vblank_start", timing::VBLANK_START as u32);
        is("master_line", timing::MASTER_PER_LINE);
        is("dots", timing::DOTS as u32);
        is("sprites", (OAM_LEN as u32 - 32) / 4);
    }

    #[test]
    fn every_entry_is_on_the_map() {
        let on_map = |c: &str| romlens_tutor::lesson::concept(c).is_some();
        for f in NUMBERS {
            assert!(on_map(f.concept) && (1..=5).contains(&f.level), "{}", f.id);
        }
        for f in SAIDS {
            assert!(on_map(f.concept) && (1..=5).contains(&f.level), "{}", f.id);
            assert!(
                f.wrong.len() >= 2 && !f.wrong.contains(&f.answer),
                "{}",
                f.id
            );
        }
        let mut ids: Vec<&str> = NUMBERS
            .iter()
            .map(|f| f.id)
            .chain(SAIDS.iter().map(|f| f.id))
            .collect();
        let n = ids.len();
        ids.sort_unstable();
        ids.dedup();
        assert_eq!(ids.len(), n, "an id is used twice");
        for (c, _) in CONCEPT_REGISTERS
            .iter()
            .chain(CONCEPT_DSP)
            .chain(CONCEPT_MNEMONICS)
            .chain(CONCEPT_TERMS)
        {
            assert!(on_map(c), "{c}");
        }
    }
}
