//! The 256-entry opcode table, written as the sixteen rows of the WDC matrix.
//!
//! Column pattern for the eight "A-op" rows (`$0x ORA`, `$2x AND`, `$4x EOR`,
//! `$6x ADC`, `$8x STA`, `$Ax LDA`, `$Cx CMP`, `$Ex SBC`): even row x1 `(dp,X)`,
//! x3 `sr,S`, x5 `dp`, x7 `[dp]`, x9 `#imm`, xD `abs`, xF `long`; odd row x1
//! `(dp),Y`, x2 `(dp)`, x3 `(sr,S),Y`, x5 `dp,X`, x7 `[dp],Y`, x9 `abs,Y`, xD
//! `abs,X`, xF `long,X`. `$89` is `BIT #imm`. The even-row x2 column holds
//! COP / JSL / WDM / PER / BRL / LDX # / REP / SEP; `$44` MVP, `$54` MVN; jumps
//! `$4C $5C $6C $7C $DC $20 $FC`; `$F4` PEA, `$D4` PEI.

use crate::cpu65816::mnemonic::Mnemonic;
use crate::cpu65816::mode::AddressingMode;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct OpcodeInfo {
    pub mnemonic: Mnemonic,
    pub mode: AddressingMode,
}

const fn op(mnemonic: Mnemonic, mode: AddressingMode) -> OpcodeInfo {
    OpcodeInfo { mnemonic, mode }
}

use AddressingMode as M;
use Mnemonic::*;

/// Opcode → mnemonic and addressing mode.
pub static OPCODES: [OpcodeInfo; 256] = [
    // $00
    op(BRK, M::Immediate8),
    op(ORA, M::DirectIndexedIndirect),
    op(COP, M::Immediate8),
    op(ORA, M::StackRelative),
    op(TSB, M::Direct),
    op(ORA, M::Direct),
    op(ASL, M::Direct),
    op(ORA, M::DirectIndirectLong),
    op(PHP, M::Implied),
    op(ORA, M::ImmediateM),
    op(ASL, M::Accumulator),
    op(PHD, M::Implied),
    op(TSB, M::Absolute),
    op(ORA, M::Absolute),
    op(ASL, M::Absolute),
    op(ORA, M::AbsoluteLong),
    // $10
    op(BPL, M::Relative8),
    op(ORA, M::DirectIndirectIndexed),
    op(ORA, M::DirectIndirect),
    op(ORA, M::StackRelativeIndirectIndexed),
    op(TRB, M::Direct),
    op(ORA, M::DirectX),
    op(ASL, M::DirectX),
    op(ORA, M::DirectIndirectLongIndexed),
    op(CLC, M::Implied),
    op(ORA, M::AbsoluteY),
    op(INC, M::Accumulator),
    op(TCS, M::Implied),
    op(TRB, M::Absolute),
    op(ORA, M::AbsoluteX),
    op(ASL, M::AbsoluteX),
    op(ORA, M::AbsoluteLongX),
    // $20
    op(JSR, M::Absolute),
    op(AND, M::DirectIndexedIndirect),
    op(JSL, M::AbsoluteLong),
    op(AND, M::StackRelative),
    op(BIT, M::Direct),
    op(AND, M::Direct),
    op(ROL, M::Direct),
    op(AND, M::DirectIndirectLong),
    op(PLP, M::Implied),
    op(AND, M::ImmediateM),
    op(ROL, M::Accumulator),
    op(PLD, M::Implied),
    op(BIT, M::Absolute),
    op(AND, M::Absolute),
    op(ROL, M::Absolute),
    op(AND, M::AbsoluteLong),
    // $30
    op(BMI, M::Relative8),
    op(AND, M::DirectIndirectIndexed),
    op(AND, M::DirectIndirect),
    op(AND, M::StackRelativeIndirectIndexed),
    op(BIT, M::DirectX),
    op(AND, M::DirectX),
    op(ROL, M::DirectX),
    op(AND, M::DirectIndirectLongIndexed),
    op(SEC, M::Implied),
    op(AND, M::AbsoluteY),
    op(DEC, M::Accumulator),
    op(TSC, M::Implied),
    op(BIT, M::AbsoluteX),
    op(AND, M::AbsoluteX),
    op(ROL, M::AbsoluteX),
    op(AND, M::AbsoluteLongX),
    // $40
    op(RTI, M::Implied),
    op(EOR, M::DirectIndexedIndirect),
    op(WDM, M::Immediate8),
    op(EOR, M::StackRelative),
    op(MVP, M::BlockMove),
    op(EOR, M::Direct),
    op(LSR, M::Direct),
    op(EOR, M::DirectIndirectLong),
    op(PHA, M::Implied),
    op(EOR, M::ImmediateM),
    op(LSR, M::Accumulator),
    op(PHK, M::Implied),
    op(JMP, M::Absolute),
    op(EOR, M::Absolute),
    op(LSR, M::Absolute),
    op(EOR, M::AbsoluteLong),
    // $50
    op(BVC, M::Relative8),
    op(EOR, M::DirectIndirectIndexed),
    op(EOR, M::DirectIndirect),
    op(EOR, M::StackRelativeIndirectIndexed),
    op(MVN, M::BlockMove),
    op(EOR, M::DirectX),
    op(LSR, M::DirectX),
    op(EOR, M::DirectIndirectLongIndexed),
    op(CLI, M::Implied),
    op(EOR, M::AbsoluteY),
    op(PHY, M::Implied),
    op(TCD, M::Implied),
    op(JML, M::AbsoluteLong),
    op(EOR, M::AbsoluteX),
    op(LSR, M::AbsoluteX),
    op(EOR, M::AbsoluteLongX),
    // $60
    op(RTS, M::Implied),
    op(ADC, M::DirectIndexedIndirect),
    op(PER, M::Relative16),
    op(ADC, M::StackRelative),
    op(STZ, M::Direct),
    op(ADC, M::Direct),
    op(ROR, M::Direct),
    op(ADC, M::DirectIndirectLong),
    op(PLA, M::Implied),
    op(ADC, M::ImmediateM),
    op(ROR, M::Accumulator),
    op(RTL, M::Implied),
    op(JMP, M::AbsoluteIndirect),
    op(ADC, M::Absolute),
    op(ROR, M::Absolute),
    op(ADC, M::AbsoluteLong),
    // $70
    op(BVS, M::Relative8),
    op(ADC, M::DirectIndirectIndexed),
    op(ADC, M::DirectIndirect),
    op(ADC, M::StackRelativeIndirectIndexed),
    op(STZ, M::DirectX),
    op(ADC, M::DirectX),
    op(ROR, M::DirectX),
    op(ADC, M::DirectIndirectLongIndexed),
    op(SEI, M::Implied),
    op(ADC, M::AbsoluteY),
    op(PLY, M::Implied),
    op(TDC, M::Implied),
    op(JMP, M::AbsoluteIndexedIndirect),
    op(ADC, M::AbsoluteX),
    op(ROR, M::AbsoluteX),
    op(ADC, M::AbsoluteLongX),
    // $80
    op(BRA, M::Relative8),
    op(STA, M::DirectIndexedIndirect),
    op(BRL, M::Relative16),
    op(STA, M::StackRelative),
    op(STY, M::Direct),
    op(STA, M::Direct),
    op(STX, M::Direct),
    op(STA, M::DirectIndirectLong),
    op(DEY, M::Implied),
    op(BIT, M::ImmediateM),
    op(TXA, M::Implied),
    op(PHB, M::Implied),
    op(STY, M::Absolute),
    op(STA, M::Absolute),
    op(STX, M::Absolute),
    op(STA, M::AbsoluteLong),
    // $90
    op(BCC, M::Relative8),
    op(STA, M::DirectIndirectIndexed),
    op(STA, M::DirectIndirect),
    op(STA, M::StackRelativeIndirectIndexed),
    op(STY, M::DirectX),
    op(STA, M::DirectX),
    op(STX, M::DirectY),
    op(STA, M::DirectIndirectLongIndexed),
    op(TYA, M::Implied),
    op(STA, M::AbsoluteY),
    op(TXS, M::Implied),
    op(TXY, M::Implied),
    op(STZ, M::Absolute),
    op(STA, M::AbsoluteX),
    op(STZ, M::AbsoluteX),
    op(STA, M::AbsoluteLongX),
    // $A0
    op(LDY, M::ImmediateX),
    op(LDA, M::DirectIndexedIndirect),
    op(LDX, M::ImmediateX),
    op(LDA, M::StackRelative),
    op(LDY, M::Direct),
    op(LDA, M::Direct),
    op(LDX, M::Direct),
    op(LDA, M::DirectIndirectLong),
    op(TAY, M::Implied),
    op(LDA, M::ImmediateM),
    op(TAX, M::Implied),
    op(PLB, M::Implied),
    op(LDY, M::Absolute),
    op(LDA, M::Absolute),
    op(LDX, M::Absolute),
    op(LDA, M::AbsoluteLong),
    // $B0
    op(BCS, M::Relative8),
    op(LDA, M::DirectIndirectIndexed),
    op(LDA, M::DirectIndirect),
    op(LDA, M::StackRelativeIndirectIndexed),
    op(LDY, M::DirectX),
    op(LDA, M::DirectX),
    op(LDX, M::DirectY),
    op(LDA, M::DirectIndirectLongIndexed),
    op(CLV, M::Implied),
    op(LDA, M::AbsoluteY),
    op(TSX, M::Implied),
    op(TYX, M::Implied),
    op(LDY, M::AbsoluteX),
    op(LDA, M::AbsoluteX),
    op(LDX, M::AbsoluteY),
    op(LDA, M::AbsoluteLongX),
    // $C0
    op(CPY, M::ImmediateX),
    op(CMP, M::DirectIndexedIndirect),
    op(REP, M::Immediate8),
    op(CMP, M::StackRelative),
    op(CPY, M::Direct),
    op(CMP, M::Direct),
    op(DEC, M::Direct),
    op(CMP, M::DirectIndirectLong),
    op(INY, M::Implied),
    op(CMP, M::ImmediateM),
    op(DEX, M::Implied),
    op(WAI, M::Implied),
    op(CPY, M::Absolute),
    op(CMP, M::Absolute),
    op(DEC, M::Absolute),
    op(CMP, M::AbsoluteLong),
    // $D0
    op(BNE, M::Relative8),
    op(CMP, M::DirectIndirectIndexed),
    op(CMP, M::DirectIndirect),
    op(CMP, M::StackRelativeIndirectIndexed),
    op(PEI, M::DirectIndirect),
    op(CMP, M::DirectX),
    op(DEC, M::DirectX),
    op(CMP, M::DirectIndirectLongIndexed),
    op(CLD, M::Implied),
    op(CMP, M::AbsoluteY),
    op(PHX, M::Implied),
    op(STP, M::Implied),
    op(JML, M::AbsoluteIndirectLong),
    op(CMP, M::AbsoluteX),
    op(DEC, M::AbsoluteX),
    op(CMP, M::AbsoluteLongX),
    // $E0
    op(CPX, M::ImmediateX),
    op(SBC, M::DirectIndexedIndirect),
    op(SEP, M::Immediate8),
    op(SBC, M::StackRelative),
    op(CPX, M::Direct),
    op(SBC, M::Direct),
    op(INC, M::Direct),
    op(SBC, M::DirectIndirectLong),
    op(INX, M::Implied),
    op(SBC, M::ImmediateM),
    op(NOP, M::Implied),
    op(XBA, M::Implied),
    op(CPX, M::Absolute),
    op(SBC, M::Absolute),
    op(INC, M::Absolute),
    op(SBC, M::AbsoluteLong),
    // $F0
    op(BEQ, M::Relative8),
    op(SBC, M::DirectIndirectIndexed),
    op(SBC, M::DirectIndirect),
    op(SBC, M::StackRelativeIndirectIndexed),
    op(PEA, M::Absolute),
    op(SBC, M::DirectX),
    op(INC, M::DirectX),
    op(SBC, M::DirectIndirectLongIndexed),
    op(SED, M::Implied),
    op(SBC, M::AbsoluteY),
    op(PLX, M::Implied),
    op(XCE, M::Implied),
    op(JSR, M::AbsoluteIndexedIndirect),
    op(SBC, M::AbsoluteX),
    op(INC, M::AbsoluteX),
    op(SBC, M::AbsoluteLongX),
];

/// The opcode for a mnemonic in a mode, when the pair exists.
pub fn opcode_for(mnemonic: Mnemonic, mode: AddressingMode) -> Option<u8> {
    OPCODES
        .iter()
        .position(|o| o.mnemonic == mnemonic && o.mode == mode)
        .map(|i| i as u8)
}
